# Generated by Django 2.2 on 2020-10-25 11:44

from django.db import migrations, models
import registration_directory.utils


class Migration(migrations.Migration):

    dependencies = [
        ('registration_directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=registration_directory.utils.rename),
        ),
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=registration_directory.utils.rename),
        ),
    ]
