version: "3.4"
services:
  backend:
    container_name: backend
    build:
      context: ./backend/
      target: local
    restart: on-failure
    command: python manage.py runserver 0:8080
    volumes:
      - ./backend:/backend
    depends_on:
      - postgres
    networks:
      - backend
      - postgres
    env_file:
      - backend/.env-local
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      target: local
    restart: on-failure
    command: ng serve --host=0.0.0.0 --port=4200
    volumes:
      - ./frontend:/frontend
    networks:
      - frontend
  postgres:
    container_name: postgres
    image: "postgres:latest"
    volumes:
      - postgres:/var/lib/postgresql/data;
    networks:
      - postgres
    env_file:
      - postgres/.env-local
  nginx:
    container_name: nginx
    build:
      context: ./nginx/
      target: local
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - backend
      - frontend

volumes:
  postgres:

networks:
  backend:
  frontend:
  postgres:
